/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    amenities: Amenity;
    testimonials: Testimonial;
    faq: Faq;
    posts: Post;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  title: string;
  description: string;
  icon?: ('heart' | 'shield' | 'utensils' | 'dumbbell' | 'book' | 'leaf' | 'wifi' | 'bus' | 'users' | 'star') | null;
  image?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  location?: string | null;
  quote: string;
  rating?: number | null;
  photo?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('general' | 'healthcare' | 'pricing' | 'amenities' | 'admission') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  category?: ('health' | 'community' | 'events' | 'tips') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedDate?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  interest?: ('active-adult' | 'residences' | 'wellness' | 'visit' | 'general' | 'other') | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'qualified' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  quote?: T;
  rating?: T;
  photo?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  category?: T;
  content?: T;
  publishedDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  interest?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  whatsapp?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  navCtaLabel?: string | null;
  navCtaLink?: string | null;
  footerAbout?: string | null;
  footerExploreHeading?: string | null;
  footerExploreLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerCareHeading?: string | null;
  footerCareItems?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  footerContactHeading?: string | null;
  footerBottomLeft?: string | null;
  footerBottomRight?: string | null;
  contactEyebrow?: string | null;
  contactTitle?: string | null;
  contactIntro?: string | null;
  contactCallLabel?: string | null;
  contactEmailLabel?: string | null;
  contactWhatsappLabel?: string | null;
  contactVisitLabel?: string | null;
  contactHoursLabel?: string | null;
  contactHoursValue?: string | null;
  contactImage?: (number | null) | Media;
  contactImageUrl?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoKeywords?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  ogImage?: (number | null) | Media;
  ogImageUrl?: string | null;
  heroBrandTitle?: string | null;
  heroBrandCaption?: string | null;
  /**
   * Small metadata line shown below the hero headline (e.g. unit count, location, status).
   */
  heroMeta?: string | null;
  heroSlides?:
    | {
        heading: string;
        subheading?: string | null;
        caption?: string | null;
        ctaText?: string | null;
        ctaLink?: string | null;
        image?: (number | null) | Media;
        /**
         * Optional external image URL. Used when no media upload is selected.
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  promiseEyebrow?: string | null;
  promiseHeading?: string | null;
  /**
   * Separate paragraphs with a blank line. Wrap words in **double asterisks** to make them bold — e.g. **The Park by Aroha**.
   */
  promiseBody?: string | null;
  promiseStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  careEyebrow?: string | null;
  careHeading?: string | null;
  careBody?: string | null;
  partnerLabel?: string | null;
  partnerUrl?: string | null;
  careMainImage?: (number | null) | Media;
  careMainImageUrl?: string | null;
  careAccentImage?: (number | null) | Media;
  careAccentImageUrl?: string | null;
  careAccentLabel?: string | null;
  careBadgeTitle?: string | null;
  careBadgeMeta?: string | null;
  missionEyebrow?: string | null;
  missionTitle?: string | null;
  missionBody?: string | null;
  visionEyebrow?: string | null;
  visionTitle?: string | null;
  visionBody?: string | null;
  facilitiesEyebrow?: string | null;
  facilitiesTitle?: string | null;
  facilitiesIntro?: string | null;
  facilityCategories?:
    | {
        title: string;
        subtitle: string;
        intro: string;
        badge?: string | null;
        icon?:
          | (
              | 'heart'
              | 'shield'
              | 'utensils'
              | 'dumbbell'
              | 'book'
              | 'leaf'
              | 'wifi'
              | 'bus'
              | 'users'
              | 'star'
              | 'sun'
              | 'home'
            )
          | null;
        items?:
          | {
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  masterPlanEyebrow?: string | null;
  masterPlanTitle?: string | null;
  masterPlanBody?: string | null;
  masterPlanImage?: (number | null) | Media;
  masterPlanImageUrl?: string | null;
  masterPlanPlaceholderLabel?: string | null;
  masterPlanPlaceholderNote?: string | null;
  residencesEyebrow?: string | null;
  residencesTitleLineOne?: string | null;
  residencesTitleLineTwo?: string | null;
  residencesIntro?: string | null;
  residenceCards?:
    | {
        title: string;
        description: string;
        image?: (number | null) | Media;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  floorplanNote?: string | null;
  /**
   * Upload the site walkthrough video. It will play muted and looped on the homepage.
   */
  walkthroughVideo?: (number | null) | Media;
  walkthroughVideoTitle?: string | null;
  walkthroughVideoCaption?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  phone?: T;
  email?: T;
  address?: T;
  whatsapp?: T;
  facebook?: T;
  instagram?: T;
  youtube?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  navCtaLabel?: T;
  navCtaLink?: T;
  footerAbout?: T;
  footerExploreHeading?: T;
  footerExploreLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerCareHeading?: T;
  footerCareItems?:
    | T
    | {
        label?: T;
        id?: T;
      };
  footerContactHeading?: T;
  footerBottomLeft?: T;
  footerBottomRight?: T;
  contactEyebrow?: T;
  contactTitle?: T;
  contactIntro?: T;
  contactCallLabel?: T;
  contactEmailLabel?: T;
  contactWhatsappLabel?: T;
  contactVisitLabel?: T;
  contactHoursLabel?: T;
  contactHoursValue?: T;
  contactImage?: T;
  contactImageUrl?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoKeywords?: T;
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  ogImageUrl?: T;
  heroBrandTitle?: T;
  heroBrandCaption?: T;
  heroMeta?: T;
  heroSlides?:
    | T
    | {
        heading?: T;
        subheading?: T;
        caption?: T;
        ctaText?: T;
        ctaLink?: T;
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  promiseEyebrow?: T;
  promiseHeading?: T;
  promiseBody?: T;
  promiseStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  careEyebrow?: T;
  careHeading?: T;
  careBody?: T;
  partnerLabel?: T;
  partnerUrl?: T;
  careMainImage?: T;
  careMainImageUrl?: T;
  careAccentImage?: T;
  careAccentImageUrl?: T;
  careAccentLabel?: T;
  careBadgeTitle?: T;
  careBadgeMeta?: T;
  missionEyebrow?: T;
  missionTitle?: T;
  missionBody?: T;
  visionEyebrow?: T;
  visionTitle?: T;
  visionBody?: T;
  facilitiesEyebrow?: T;
  facilitiesTitle?: T;
  facilitiesIntro?: T;
  facilityCategories?:
    | T
    | {
        title?: T;
        subtitle?: T;
        intro?: T;
        badge?: T;
        icon?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  masterPlanEyebrow?: T;
  masterPlanTitle?: T;
  masterPlanBody?: T;
  masterPlanImage?: T;
  masterPlanImageUrl?: T;
  masterPlanPlaceholderLabel?: T;
  masterPlanPlaceholderNote?: T;
  residencesEyebrow?: T;
  residencesTitleLineOne?: T;
  residencesTitleLineTwo?: T;
  residencesIntro?: T;
  residenceCards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  floorplanNote?: T;
  walkthroughVideo?: T;
  walkthroughVideoTitle?: T;
  walkthroughVideoCaption?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}